export const CHAT_WS_EVENTS = {
  MESSAGE_SEND: 'message:send',
  MESSAGE_NEW: 'message:new',
  MESSAGE_DELIVERED: 'message:delivered',
  MESSAGE_SEEN: 'message:seen',
  MESSAGE_RECALL: 'message:recall',
  TYPING_START: 'typing:start',
  TYPING_STOP: 'typing:stop',
  PRESENCE_UPDATE: 'presence:update',
  CONVERSATION_UPDATED: 'conversation:updated',
  SYNC_PULL: 'sync:pull',
  SYNC_PUSH: 'sync:push',
  JOIN_CONVERSATION: 'conversation:join',
  LEAVE_CONVERSATION: 'conversation:leave',
} as const;
