import { ENUM_PAGINATION_ORDER_DIRECTION_TYPE } from 'src/common/pagination/enums/pagination.enum';

//! Pagination default variable
export const PAGINATION_DEFAULT_PER_PAGE = 10;
export const PAGINATION_DEFAULT_MAX_PER_PAGE = 100;

export const PAGINATION_DEFAULT_PAGE = 1;
export const PAGINATION_DEFAULT_MAX_PAGE = 20;

export const PAGINATION_DEFAULT_ORDER_BY = 'updatedAt';
export const PAGINATION_DEFAULT_ORDER_DIRECTION: ENUM_PAGINATION_ORDER_DIRECTION_TYPE =
    ENUM_PAGINATION_ORDER_DIRECTION_TYPE.DESC;

export const PAGINATION_DEFAULT_AVAILABLE_ORDER_BY: string[] = ['updatedAt'];
export const PAGINATION_DEFAULT_AVAILABLE_ORDER_DIRECTION: ENUM_PAGINATION_ORDER_DIRECTION_TYPE[] =
    [
        ENUM_PAGINATION_ORDER_DIRECTION_TYPE.ASC,
        ENUM_PAGINATION_ORDER_DIRECTION_TYPE.DESC,
    ];
